// Builds dist/ from tokens.json with no dependencies:
//   tokens.css  CSS custom properties. Dark is the default; light applies when
//               the device asks for it (prefers-color-scheme) unless the page
//               pins a theme with data-theme="dark" | "light".
//   theme.css   a Tailwind v4 `@theme inline` block mapping the tokens to
//               utility namespaces (bg-bg-100, text-ink, rounded-md, ...).
//   type.css    one class per type style (.display-xl, .body, .kicker, ...).
//   index.js    the resolved token values as a typed object, for React Native,
//               charts and anything that cannot read CSS.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens.json"), "utf8"));
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const themes = tokens.color.themes.map((t) => t.id);
const first = themes[0];
const ALIAS = /^\{([A-Za-z0-9_.-]+)\}$/;

/** The CSS value of a token in one theme; an alias becomes var(--name). */
export function themedValue(token, theme) {
  const raw =
    typeof token.value === "string"
      ? token.value
      : (token.value[theme] ?? token.value[first]);
  const alias = ALIAS.exec(raw);
  return alias ? `var(--${alias[1]})` : raw;
}

const declarations = (entries) =>
  entries.map(([n, v]) => `  --${n}: ${v};`).join("\n");

/** Per-theme declarations: colour and shadow families. */
function themedEntries(theme) {
  const out = [];
  for (const family of ["color", "shadow"]) {
    for (const token of tokens[family]?.tokens ?? []) {
      out.push([token.name, themedValue(token, theme)]);
    }
  }
  return out;
}

/** Theme-independent declarations: spacing, radius, layout and font stacks. */
function staticEntries() {
  const out = [];
  for (const family of Object.keys(tokens)) {
    if (["name", "version", "meta", "color", "shadow", "type"].includes(family))
      continue;
    for (const token of tokens[family].tokens ?? [])
      out.push([token.name, token.value]);
  }
  for (const [key, stack] of Object.entries(tokens.type.families)) {
    out.push([`font-${key}`, stack]);
  }
  return out;
}

const scheme = (theme) => `  color-scheme: ${theme};`;

function buildTokensCss() {
  const parts = [
    `/* Generated by @mishrashardendu22/observatory-tokens from tokens.json. Do not edit. */`,
    `:root {\n${scheme(first)}\n${declarations(themedEntries(first))}\n${declarations(staticEntries())}\n}`,
  ];
  for (const theme of themes.slice(1)) {
    const body = `${scheme(theme)}\n${declarations(themedEntries(theme))}`;
    parts.push(
      `@media (prefers-color-scheme: ${theme}) {\n  :root:not([data-theme]) {\n${body.replace(/^/gm, "  ")}\n  }\n}`,
    );
    parts.push(`[data-theme="${theme}"] {\n${body}\n}`);
  }
  parts.push(
    `[data-theme="${first}"] {\n${scheme(first)}\n${declarations(themedEntries(first))}\n}`,
  );
  return `${parts.join("\n\n")}\n`;
}

function buildThemeCss() {
  const lines = [];
  for (const token of tokens.color.tokens)
    lines.push(`  --color-${token.name}: var(--${token.name});`);
  for (const token of tokens.shadow?.tokens ?? [])
    lines.push(`  --${token.name}: var(--${token.name});`);
  for (const token of tokens.radius.tokens)
    lines.push(`  --${token.name}: var(--${token.name});`);
  for (const token of tokens.spacing.tokens)
    lines.push(
      `  --spacing-${token.name.replace(/^space-/, "")}: var(--${token.name});`,
    );
  for (const key of Object.keys(tokens.type.families))
    lines.push(`  --font-${key}: var(--font-${key});`);
  return `/* Generated. Tailwind v4 theme: @import "@mishrashardendu22/observatory-tokens/theme.css" after tokens.css. */\n@theme inline {\n${lines.join("\n")}\n}\n`;
}

function buildTypeCss() {
  const blocks = [];
  for (const group of tokens.type.groups) {
    for (const style of group.styles) {
      const family = style.family ?? group.family;
      const decl = [
        `font-family: var(--font-${family});`,
        `font-size: ${style.fontSize};`,
        `line-height: ${style.lineHeight};`,
        `font-weight: ${style.fontWeight};`,
      ];
      if (style.letterSpacing)
        decl.push(`letter-spacing: ${style.letterSpacing};`);
      if (style.fontStyle) decl.push(`font-style: ${style.fontStyle};`);
      if (style.name === "kicker") decl.push("text-transform: uppercase;");
      if (style.name === "stat-value")
        decl.push("font-variant-numeric: tabular-nums;");
      blocks.push(`.${style.name} {\n  ${decl.join("\n  ")}\n}`);
    }
  }
  return `/* Generated. One class per type style of the Observatory design system. */\n${blocks.join("\n\n")}\n`;
}

function buildIndex() {
  const color = {};
  for (const token of tokens.color.tokens) {
    color[token.name] = Object.fromEntries(
      themes.map((t) => [t, themedValue(token, t)]),
    );
  }
  const flat = (family) =>
    Object.fromEntries(
      (tokens[family]?.tokens ?? []).map((t) => [t.name, t.value]),
    );
  const shadow = {};
  for (const token of tokens.shadow?.tokens ?? []) {
    shadow[token.name] = Object.fromEntries(
      themes.map((t) => [t, themedValue(token, t)]),
    );
  }
  const type = {};
  for (const group of tokens.type.groups) {
    for (const style of group.styles) {
      type[style.name] = {
        family: style.family ?? group.family,
        fontSize: style.fontSize,
        lineHeight: style.lineHeight,
        fontWeight: style.fontWeight,
        ...(style.letterSpacing ? { letterSpacing: style.letterSpacing } : {}),
      };
    }
  }
  const data = {
    name: tokens.name,
    version: tokens.version,
    themes,
    color,
    shadow,
    spacing: flat("spacing"),
    radius: flat("radius"),
    layout: flat("layout"),
    fonts: tokens.type.families,
    type,
  };
  const js = `// Generated by @mishrashardendu22/observatory-tokens from tokens.json. Do not edit.
export const tokens = ${JSON.stringify(data, null, 2)};
export const themes = tokens.themes;
/** var(--name) for use in inline styles and chart libraries. */
export const cssVar = (name) => \`var(--\${name})\`;
/** Chart series and chrome, as CSS variable references. */
export const chart = {
  primary: "var(--chart-primary)",
  failed: "var(--chart-failed)",
  skipped: "var(--chart-skipped)",
  grid: "var(--chart-grid)",
  axis: "var(--chart-axis)",
};
`;
  const names = (obj) =>
    Object.keys(obj)
      .map((k) => JSON.stringify(k))
      .join(" | ");
  const dts = `// Generated by @mishrashardendu22/observatory-tokens from tokens.json. Do not edit.
export type ThemeId = ${themes.map((t) => JSON.stringify(t)).join(" | ")};
export type ColorToken = ${names(color)};
export type SpacingToken = ${names(data.spacing)};
export type RadiusToken = ${names(data.radius)};
export type LayoutToken = ${names(data.layout)};
export type ShadowToken = ${names(shadow)};
export type TypeStyle = ${names(type)};
export interface TypeStyleValue { family: string; fontSize: string; lineHeight: string; fontWeight: number; letterSpacing?: string }
export interface Tokens {
  name: string;
  version: number;
  themes: ThemeId[];
  color: Record<ColorToken, Record<ThemeId, string>>;
  shadow: Record<ShadowToken, Record<ThemeId, string>>;
  spacing: Record<SpacingToken, string>;
  radius: Record<RadiusToken, string>;
  layout: Record<LayoutToken, string>;
  fonts: Record<string, string>;
  type: Record<TypeStyle, TypeStyleValue>;
}
export declare const tokens: Tokens;
export declare const themes: ThemeId[];
export declare function cssVar(name: ColorToken | SpacingToken | RadiusToken | LayoutToken | ShadowToken | string): string;
export declare const chart: { primary: string; failed: string; skipped: string; grid: string; axis: string };
`;
  return { js, dts };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(dist, "tokens.css"), buildTokensCss());
  writeFileSync(join(dist, "theme.css"), buildThemeCss());
  writeFileSync(join(dist, "type.css"), buildTypeCss());
  const { js, dts } = buildIndex();
  writeFileSync(join(dist, "index.js"), js);
  writeFileSync(join(dist, "index.d.ts"), dts);
  console.log(
    `built ${themes.length} themes, ${tokens.color.tokens.length} colours -> ${dist}`,
  );
}
